update_interval_s: 60
google_username: eDhellweiSs
google_password: pcbitzihbxcebbzk
todoist_api_token: 97fcac5b374217fc71cf444d055bc76fe6cab00e
healthcheck: # optional: configure some kind of healtcheck endpoint providing service monitoring, e.g. https://healthchecks.io/
  url: https://hc-ping.com/someuuid
  period_min: 30
untitled_notes: # optional: move all untitled notes to todoist inbox
  add_label: 'keep' # required: add label to todoist note
  due_str_en: 'today' # optional: you can set a due date in english here
keep_lists:  # list your keep lists on this level
  - Todoist:
      sync_labels: false # required: transfer labels from gkeep lists to todoist items
      due_str_en: 'today' # optional: you can set a due date in english here
      # if todoist_project is not set your task will go into the todoist inbox
  - Fam:
      sync_labels: true
      assignee_email: 'doris55.mudry@bluewin.ch' # optional: the email of the person to be assigned, requires todoist_project to be a shared project.
      todoist_project: 'Famille' # not optional in this case, should be a shared project
  - Achat:
      sync_labels: false
      todoist_project: 'BUYLIST' # optional: you can choose a project for todoist here
  - Test:
      sync_labels: false
